Train:
  experiment_name: 'convnext_castinv'
  device: 'cuda'
  epochs: 40
  val_epoch: 3
  checkpoint_epoch: 50
  start_epoch: 0
Data:
  train_imgs: '../../data/HUBMAP_HPA_22/hubmap_768_whole/train_images/'
  masks: '../../data/HUBMAP_HPA_22/hubmap_768_whole/train_masks/'
  labels: '../../data/HUBMAP_HPA_22/hubmap_orig/train.csv'
  nfolds: 4
  fold: 2
  seed: 309
Loader:
  batch_size: 4
  num_workers: 4
Architecture:
  encoder: 'convnext_tiny'
  weights: '../pretrained_models/convnext_tiny_1k_224_ema.pth'
Logging:
  wandb_project: 'segmap'
Eval:
  checkpoint_epoch: 39
  neptune:
    root: '../../data/NEPTUNE/'
    he: 'HE_glom_capsule'
    pas: 'pas-gcapsule-data'
    sil: 'sil-gcapsule-data'
    tri: 'tri-gcapsule-data'
  aidpath:
    imgs: '../../data/Adipath_processed/images_1024/'
    masks: '../../data/Adipath_processed/masks_1024/'
  hubmap21_kidney:
    imgs: '../../data/Hubmap_21_Kidney/train/'
    masks: '../../data/Hubmap_21_Kidney/masks/'
