Train:
  experiment_name: 'test'
  device: 'cuda'
  epochs: 80
  val_epoch: 3
  checkpoint_epoch: 50
  start_epoch: 0
Data:
  train_imgs: '../../thesis/data/HUBMAP_HPA_22/hubmap_768_whole/train_images/'
  masks: '../../thesis/data/HUBMAP_HPA_22/hubmap_768_whole/train_masks/'
  labels: '../../thesis/data/HUBMAP_HPA_22/hubmap_orig/train.csv'
  nfolds: 4
  fold: 2
  seed: 309  
Loader:
  batch_size: 4
  num_workers: 4
Architecture:
  encoder: 'resnet50'  
  weights: '' # Initialized from 'segmentation models pytorch' pretrained weights
Logging:
  wandb_project: 'segmap'
Eval:
  checkpoint_epoch: 79
  neptune:
    root: '../../thesis/data/NEPTUNE/'
    he: 'HE_glom_capsule'
    pas: 'pas-gcapsule-data'
    sil: 'sil-gcapsule-data'
    tri: 'tri-gcapsule-data'
  aidpath:
    imgs: '../../thesis/data/Adipath_processed/images_1024/'
    masks: '../../thesis/data/Adipath_processed/masks_1024/'
  hubmap21_kidney:
    imgs: '../../thesis/data/Hubmap_21_Kidney/train/'
    masks: '../../thesis/data/Hubmap_21_Kidney/masks/'

  