Global:
  experiment_name: 'test'
  device: 'cuda'
  epochs: 1
  val_epoch: 3
  checkpoint_epoch: 50
  start_epoch: 0
Data:
  train_imgs: '../../thesis/data/HUBMAP_HPA_22/hubmap_768_whole/train_images/'
  masks: '../../thesis/data/HUBMAP_HPA_22/hubmap_768_whole/train_masks/'
  labels: '../../thesis/data/HUBMAP_HPA_22/hubmap_orig/train.csv'
  nfolds: 4
  fold: 2
  seed: 309  
Loader:
  batch_size: 4
  num_workers: 4
Architecture:
  encoder: 'resnet50' # 'convnext_tiny'  
  weights: '../pretrained_models/convnext_tiny_1k_224_ema.pth'
Logging:
  wandb_project: 'segmap'